Vagrant.configure(2) do |config|
  config.vm.box = "bento/ubuntu-16.04"
  config.vm.network "forwarded_port", guest: 8080, host: 8080
  # config.vm.network "forwarded_port", guest: 80, host: 8081
  # PostgreSQL Server port forwarding
  config.vm.network "forwarded_port", guest: 5432, host: 5555

  # config.vm.provider :aws do |aws, override|
  #   aws.access_key_id = ""
  #   aws.secret_access_key = ""
  #
  #   aws.keypair_name = ""
  #   aws.ami = ""
  #   aws.security_groups = ['']
  #
  #   override.ssh.username = "ubuntu"
  #   override.ssh.private_key_path = ""
  # end

  #Conf add para mais uma placa de rede.
  config.vm.network "public_network", bridge: 'en0: Wi-Fi (AirPort)', auto_config: false
  config.vm.provision "shell",
                      run: "always",
      inline: "ifconfig enp0s8 192.168.0.100 netmask 255.255.255.0 up"

  #Personalizar vm
  config.vm.provider :virtualbox do |vb|
        vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
        vb.customize ["modifyvm", :id, "--memory", 1024]
        vb.customize ["modifyvm", :id, "--cpus", 2]
        vb.customize ["modifyvm", :id, "--name", "helpdesk"]
  end

  config.vbguest.auto_update = false
  config.vbguest.no_remote = false

  config.vm.provision "shell", path: "manifests/bootstrap.sh"
  config.vm.provision "puppet" do |puppet|
    puppet.options = "--verbose --debug"
    puppet.manifests_path = "manifests"
    # puppet.manifest_file = "default.pp.pp"
  end

end
