Vagrant.configure(2) do |config|
  config.vm.box = "bento/ubuntu-16.04"
  # config.vm.network "forwarded_port", guest: 8080, host: 8080
  # PostgreSQL Server port forwarding
  config.vm.network "forwarded_port", guest: 5432, host: 5555

  #Conf add para mais uma placa de rede.
  config.vm.network "public_network", bridge: 'en0: Wi-Fi (AirPort)', auto_config: false
  config.vm.provision "shell",
                      run: "always",
      inline: "ifconfig enp0s8 192.168.0.100 netmask 255.255.255.0 up"

  #Personalizar vm
  config.vm.provider :virtualbox do |vb|
        vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
        vb.customize ["modifyvm", :id, "--memory", 512]
        vb.customize ["modifyvm", :id, "--cpus", 1]
        vb.customize ["modifyvm", :id, "--name", "helpdesk"]
  end

  config.vbguest.auto_update = false
  config.vbguest.no_remote = false

  config.vm.provision "shell", inline: <<-SHELL
  	sudo apt-get update
  	sudo apt install puppet-common
  SHELL

  config.vm.provision "puppet" do |puppet|
    puppet.manifests_path = "manifests"
  end
end
