Vagrant.configure("2") do |config|
  	config.vm.box = "precise64.box"
  	config.vm.box_url = "opscode-ubuntu-14.04.box"
    	config.vm.network "public_network", ip: "192.168.0.100"

   	#config.vm.provision "shell", path: "scripts/0-update.sh"

	config.vm.provider :virtualbox do |vb|
    	vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    	vb.customize ["modifyvm", :id, "--memory", 512]
    	vb.customize ["modifyvm", :id, "--name", "producao"]
	end
end
